[build]
  command = "npm run build"
  publish = "dist"

# توجيه www.fll.sa إلى fll.sa
[[redirects]]
  from = "https://www.fll.sa/*"
  to = "https://fll.sa/:splat"
  status = 301
  force = true

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
